project:
  type: book

book:
  title: "Autism: A spectrum of possibilities"
  subtitle: "Handbook for people living with Autism in India"
  author: "Farmhill Learning Community"
  date: "9/24/2024"

  repo-url: https://github.com/farmhill-learning/autism-guide/

  chapters:
    - index.qmd
    - about.qmd
    - history.qmd
    - identification-causes.qmd
    - part: People's Perspectives
      chapters:
    - perspectives.qmd
    - part: Diagnosis & Early Intervention
      chapters:
      - diagnosis.qmd
      - next-steps.qmd
      - early-intervention.qmd
    - cures-and-remedies.qmd
    - education.qmd
    - work.qmd
    - adulting.qmd
    - resources.qmd 
    - references.qmd

bibliography: references.bib

# format:
#   html:
#     theme: cosmo
#   pdf:
#     documentclass: scrreport
#     papersize: a4
#     toc: true
#     toc-depth: 3
#     toc-title: "Table of contents"
#     number-sections: true
#     number-depth: 2
#     geometry:
#       - inner=3cm
#       - outer=4cm
#       - top=3cm
#       - bottom=4cm
#       - headsep=22pt
#       - headheight=11pt
#       - footskip=33pt
#       - ignorehead
#       - ignorefoot
#       - heightrounded
