---
format:
  html:
    include-after-body:
       - "_includes/load-comments.html"
---


# Parents of children in Early Intervention


The following are the perspectives gathered from parents of four children between the ages 5 to 8 years. All the children are in early intervention through ABA and/or Occupation Therapy (OT) and speech therapy. The children are not in formal school and the mothers typically spend their entire time taking care of the children. These perspectives were gathered through in-person interviews in August 2024. 

## Profiles

S-Am

S is a housewife who loves spending time with children and cooking for them. She says she would think of dishes her children would like and try out new items all the time. As a mother of 2 children, her day usually goes by in taking care of and spending time with the children. Am is the 2nd child, currently 6 years old, loves to play and arrange things in a linear fashion. Am enjoys fruits, and food, especially spicy chicken. Am is taking ABA sessions for 2 hours a day.

P-M 

P loves stitching and was doing it for a living until she got married. 2 children later, she has dedicated her time to taking care of them. M, the older son is 7 years old and was diagnosed when he was 3 years old. He would want a new toy everyday and the interest with a toy wouldn’t last for more than 10-15 minutes. He has always loved going to the park, and recently he has also started asking for going to the shop, understanding that we buy things from a shop. Now, he also senses that when the mother says she is going out, it means she won’t be there for sometime, so he asks to go along. M challenges everyone working with him with his head banging behavior. M takes ABA sessions along with OT currently.

Y-An

Y has a masters degree in Electronics and Communication and worked as a lecturer and HR consultant until she had a child. Y enjoys watching devotional material on her mobile when she is free. She is currently a housewife who is focusing on her children. Y and her 2 children relocated from Barcelona recently to seek ABA therapy for her 5 year old son, An. An is pre-verbal as of now and gets excited when he sees spinning objects. He also seems to enjoy traveling in any vehicle, and playing with water. An has just started ABA sessions and Y is looking forward to seeing how this pans out for An.

J-S

J completed her MA in history and B.ed. She is a government school teacher and has been on leave for the last 3 years to take care of children. Her 1st born, S who is 8 years old now, was diagnosed when he was around 3 years old. S says he loves reading books related to history and enjoys fine arts but there has not been any time for them recently. S is attending ABA sessions now for 1.5 years and J also actively participates in his sessions. S has started to communicate his feelings, started to know appropriate actions in appropriate places (for example, he knows park is for playing and temple is for praying.) S has also started to choose his dress and dress himself up. Recently he has also started to flush the toilet and clean his hands after that, all by himself. J was gleaming as she expressed all of this. They are also able to take him to functions and manage him. That way, there has been a lot of social learning in the last 1.5 years.


## Early signs and diagnosis
What were some early signs or behaviors that made you think your child might be different? What prompted you to seek a diagnosis for your child?

S-Am

Am used to say Dada and Mumma. Around 2 years of age, he stopped saying those words. He would also play by himself mostly. His grandfather visited that time and we all felt something was off. When he was 2 years and 5 months, we took him to the doctor as he was now also becoming more hyper. During the lockdown time, we also saw that he started lining up toys. It started with toys and it went on to anything and everything he could put his hand on. The doctor did some assessments and symptom checks and told us he has Autism.

P-M

M didn’t talk when he was 2 years old. When he was about 2.5 years old, there was an incident when he was at his grandparents place where he woke them up around 2-3am and started dancing on the bed. This happened once or twice. He got a fever when he was around 3 years old and while we took him to the doctor then, we expressed this concern and they suggested we take him for an assessment. We were told he has Autism and that there is no cure, but can be made manageable with therapy. He was 3 years old when he got diagnosed.

Y-An

* No response to name call
* He liked to watch things that were spinning
* He would line up objects
* There was also no eye contact

We took him to the physician in Barcelona when he was 2 years old and they suspected Global Developmental Disorder (GDD) and at 3.5 years old he was diagnosed with Autism Spectrum disorder Level II as per their classification system.

J-S

Till S was 1 year old, everything seemed very normal. We started noticing evident signs only after he was 2 years old. He was not pointing, no eye contact and he also didn't talk. When we noticed that he was not talking, we took him to the doctor. S was 2.5 years old by then. They saw him and said that it looks like symptoms of Autism Spectrum Disorder. We did not take that seriously and started school when S was 3 years old. After teachers there pointed out concerns, we again visited a psychologist for the 3rd time and got a detailed report on the diagnosis.

## Just after diagnosis

What were your feelings and thoughts before and immediately after the diagnosis? Was there a period of uncertainty?

S-Am

I didn’t understand what was going on. I had been believing that everything was normal. How could something be wrong now? I cried a lot. We did not understand and we were not satisfied either. So we wanted to get a 2nd opinion and went to NIMHANS. There they said symptoms are there but also told us not to worry and fear so much as he will be fine slowly. We were still confused.

P-M

I was so confused because we did not know the head or tail of Autism and no one gave us a clear picture. He was diagnosed at NIMHANS and they suggested we take their therapy that happens once in every 3 months, but no more information was given. Both my husband and I were very upset. I didn’t eat for about a week and kept crying. Then I had to tell myself that I need to be strong for my son and I have to change. Yet, for about a year things were uncertain as M was taking therapy only at NIMHANS once every 3 months and we did not know how to manage him nor did we see any improvements.  I felt helpless as managing 2 children was difficult. My mother would come for 1 week or 2 and help out, but I had to run the show.

Y-An

After the possible GDD diagnosis when we went for review at 3.5 years, I kept praying that nothing should be wrong. After hearing the word, I cried in front of the doctor. There was fear of the future and it took me 2-3 months to accept the fact and now I am hopeful that there will be something that can be done to manage this. An was attending school back then and they were very supportive and caring. A special educator would come and teach him once or twice a week and ensure there is some learning happening. At 2 years when they said he might have GDD itself I started looking up and reading and enquiring about the various possibilities. So after the Autism diagnosis there was no period of uncertainty as such. 

J-S

The term sounded like Greek and latin. We have never heard of this before. We were very worried. S was our first child. He was born 4 years after our marriage and through treatment. He was very precious to us. That 1 year after that was very difficult. S was getting more hyper and aggressive. I was still processing this. I used to get very irritated and show my frustration to my husband. My husband was in a better place due to the way he generally sees things and would say “This is not a problem we created for ourselves. This is God-given and there will also be a solution to this.” I also got pregnant with my 2nd child that year, so I had to take care of myself. Then I became calmer with the support of my family.

## Sources of information

Where did your knowledge of autism and how to work with it come from initially? Was it helpful? When and where did you find the most useful knowledge so far?

S-Am

To be honest, I am still not sure if I know it all or if I have understood what is going on with Am. We hear different opinions from different people and it is more confusing. We don’t know what is right and what is wrong yet. Some ask us to stop everything, some ask us to take ABA, Speech and OT. I am still confused if I am doing right by Am. So I can’t say if I actually have the knowledge I need to have. The resources I have collected so far are only through other parents. I am not experienced with technology also. Anything I need, I ask my older child and he looks for it and gives.

P-M

My knowledge has majorly been from Google. Even the current ABA center, SCA, I found out myself through google. At a rehab center M went to initially, they gave us some understanding, but Google has been helpful for me.

Y-An

My knowledge came from doctors, specialists and fellow parents. The most useful knowledge I have found so far is from fellow parents. Hearing their experiences of how they approached or what they did has helped me in shifting perspectives and taking decisions.

J-S

It mostly came from professionals, where we went to seek diagnosis/ therapy. From the detailed report is where I gained the most clarity. And now the ABA sessions here are helping me to learn managing S. And this has been the most useful knowledge for me so far.

## Initial steps and alternatives 

What initial steps did you take after diagnosis? What were the alternatives you considered? How did it work out?

S-Am

One of the doctors suggested group therapy at a rehab center and we went ahead and enrolled him there. He went for group sessions for 1 year, but there were no changes. We consulted with the doctor again and he suggested we go for one to one sessions. When AM was 3.5 years old he started one to one sessions and would attend group sessions as well. They also recommended medication for him to sleep as he was not sleeping at all. We gave him the medication, but since I saw that he was not sleeping, I stopped it myself. The group and one to one sessions went on for a year but we were not satisfied as we were still confused. There was no clarity about why we are doing what we are doing. There was no transparency at the center also. When he was 4.5 years old we started ABA sessions. That is again from parents’ suggestions. In the last 1.5 years I have an idea and I am able to see what is being done to Am. We see that it is working too.

Alternatives, we gave him homeopathy medicines for his sleep when he was 2.5 years old as suggested by a doctor. We stopped when he started to sleep at night. We didn’t want him to become dependent on medicines as Am loves medicines because of its sweet taste. In our house, we lock medicines in the locker like we lock up gold because of this.

P-M

We took the therapy they suggested at NIMHANS once every 3 months for half an hour each session. He was also given medicines for his hyperactiveness. We were not satisfied and on the lookout for help about knowing what is to be done. During one such instance when my husband who is working as a driver expressed our concern to one of the doctors he was driving for, they suggested a rehab center. There they started him on OT, ST and infant sessions. After 2-3 months speech therapy sessions stopped, and also he was doing well. So they suggested we take him to school now. At school they found him to be too hyper and having low sitting tolerance. Now we were looking for options that offered school and therapy and I understood we needed ABA for working on his sitting tolerance. When I was searching on these bases, the ABA Center SCA popped up. So we have started ABA here now. 

Y-An

In the Spanish system, they don’t want to label or do any therapy until the child is above 3 years. So only after the diagnosis at 3.5 years, we started speech and OT where An would have 1 session of each every week. He attended this for about a year and when we came to India for vacation, we met a developmental pediatrician and from her suggestion to try ABA for a year or so, my children and I have moved to India now. Alternatives I didn’t consider as much as there are only so many options available back in Spain. They have sensory integration therapy, then there is speech and occupational therapy. We considered homeopathy after one of our relatives who is a homeopathic doctor suggested, but we are yet to  discuss and take that forward.  

J-S

Since we didn’t take it seriously the first time, we right away started S with school. After the 2nd consultation is when we started him on therapies. They suggested we take Speech, OT and Behavior therapy. We found a center closer to our house for behavior therapy and started therapy there. We found other places for Speech and OT too.
We tried Homeopathy because my husband’s friend suggested for S’s aggressiveness. We stopped in a few months time as there were no changes. We also tried Ayurveda Panchakarma treatment for 8 months. We found that also useless. It was time consuming and also costly. We tried allopathy medicines for his behaviors. It showed results. That’s when we stopped Ayurveda. S was also attending school with a shadow teacher and a caretaker. After a teacher suggested this center for ABA, we have stayed here as we are seeing a lot of progress in S now.

Editor's note: While some of the parents mention alternatives, we do not endorse any of them. Many of the alternatives that parents try are not evidence based. Some can be outright dangerous. Please see @sec-alternatives for a detailed discussion of alternative approaches and why one should be cautious about them. 

## Early intervention choices and impact

What early intervention did you settle on and how is it going for the child and you? How do you think it has impacted your child, you and your family?

S-Am

We have settled on ABA and OT for now. So far to figure things out and see what is working and not working itself took us some time. There has been so much confusion for us with regard to what to do. He is one person but there are so many different opinions. We are spending money and time and we expect it to be worth it. We have shelled out a lot of money so far and it has impacted our family that way. 

P-M

Occupational therapy, Speech therapy and Applied Behavioral Analysis is what we settled on. I think they have all helped us in knowing how to manage him. We are in a better place from where we started. 

Y-An

We settled on OT, Speech initially as he was not talking. Speech therapy was good there maybe but I don’t think it worked for An. We are taking ABA after the doctor’s suggestion in India now. That has definitely left an impact on the family. My husband is managing alone and the 3 of us are here at my parents’ place. It’s a lot of stress for the both of us as parents, but we have hope. Other than that I think as a family now we have become more understanding of each other and we see more positivity. My husband has become more patient now, I feel. An is more settled now because of the interventions we have done so far. An’s sister also shares a good bond with him and takes care of him whenever necessary. She was confused initially as to why An is behaving a certain way. But once we explained, she understood him. For her also, shifting to India was a major shift as the schooling systems are very different and she is getting accustomed.

J-S

After a point we felt like we were taking too many treatments and they were hard on our pockets too. So we stuck with Behavior therapy. S was 7 years old by then. After coming to the ABA center, we have been here for the past 1.5 years now. This is going well. S has become manageable and that is a huge blessing to our family. I feel hopeful as it looks like I am on the right path. 

## Choosing the interventions 

What factors influenced you to settle on this early intervention?

S-Am

Some factors I took into consideration before settling on one are:

* If it’s working or not working
* Occupational therapy - we realized he requires to relax/ calm down physically due to his hyperactive nature
* Speech therapy - we took it because he wasn’t talking.
* ABA - doctor suggested that it will improve sitting tolerance and that it will prepare him for school.

P-M

Google knowledge. Whatever google suggested and I read, we took blindly.

Y-An

OT we had to take as he was hyperactive. Speech therapy, we took it because he wasn’t talking. ABA we are taking after the doctor's suggestion. Now I realize that for speech sessions to work, he should be having sitting tolerance and attention.

J-S

I came to each therapy through suggestions. What has helped me settle here is that I see progress and when I look back I see that the therapists work with dedication and the session timings are longer here. In most centers each session is only for 45 minutes and it goes in settling down itself. There is not much learning happening. How much my child is learning is also a factor I have looked into.

## Managing self and family

How are you managing yourself and your family through this?

S-Am

Managing our family has been difficult. When I spend time with the 2 children I feel like I have to deal with 2 different minds. My older son understands, but I feel like I am spending less time with him. Even while I am with Am, I keep thinking about what he would be doing. Husband is working full time.

P-M

All of it put together did take a toll on us as it was only me and my husband taking care of two children, mostly me. It’s a little easier now as the younger child is going to school. I am able to manage M’s schedule better while he goes to school.

Y-An

At this point, I am not thinking about myself at all. My personal life is not in the radar. After my first kid itself priorities started to change and now after An, he is the first priority. For now here in India, I have my mother’s support. So a huge chunk of my responsibilities otherwise, household chores, is taken care of. My daughter has also started to manage herself. When An was born, she was already 8 years old, so managing 2 children has not been a problem for me. My husband is managing himself back in Spain. The good thing here is that this decision was not forced upon anyone. It is mutual and a collective decision. We thought we should not regret not trying this option. So we all are up for trying this for 1 year and seeing where it takes us.

J-S

My family supports me immensely through this process. I cannot imagine doing any of this without their support. I am very grateful to my mother, brother and husband. They have extended their best support possible during testing times. Now my younger kid goes to school and I come with S for his therapies. S’s behaviors are also manageable so I am able to manage both my kids now.

## Future - Hopes and apprehensions

What are your hopes and apprehensions as you think of the future for your child?

S-Am

My hope is that he becomes independent and is able to manage himself irrespective of whether my older son takes care of him. My fear is the question “Who after me for him?”

P-M

I hope that M is independent and can do without my help. My fear is also on the same lines. After me, what and who is a question that keeps lingering on my mind.

Y-An

About the future, I don’t want to think much as it is uncertain. I am in the mindset of doing whatever it takes in the present. We never know what will happen tomorrow. Let’s do whatever has to be done in the present, and the Almighty will take care of the rest. I put my energy into thinking about what I can do today.

J-S

Hopes - He should be independent as much as possible. Financially we should build and keep as much as possible for him to support himself. If he is able to manage, then it would be good. I try to improve the sibling bond in hope that their bond would be supportive.
Fear - They are slowly reducing as I see changes in S now. 

## Advice for other parents

What advice would you give to other parents who are just starting this journey?

S-Am

My advice would be for parents to start whatever has to be done, immediately and not think too much and waste time. Try and figure it out. Do whatever has to be done for now.

P-M

My advice would be to be understanding of the child and not compare any child with another child. Keep your focus on the child during their primary years.

Y-An

Believe in the almighty and his plans
Trust the process
When 1 door closes, see the 10 windows that are still open
Put the efforts you have to put in and trust it. Things will definitely change 1 day.
I also have advice for the parents of neurotypical children out there - Be supportive, if you can’t then at least do not be hurtful or harmful. Just let us parents be and don’t pass your judgements.

J-S

Spend as much time with children and keep observing
Take suggestions of others into account but do your research and choose.
Accept the reality and take care of yourself during the process
This is God’s creation - give all the support, love and care for the child
To the families of neurotypical children - Support parents of neurodiverse kids and don’t get into the blame game.



