---
format:
  html:
    include-after-body:
       - "_includes/load-comments.html"
---

# Early Intervention

Once a child is diagnosed with autism and the parents have made some sort of peace with the diagnosis, the next question is, what do we do to help the child?

This is when we talk about a variety of approaches called ‘early interventions.’ Early interventions like occupational therapy, speech therapy, and in some cases behavioral therapy are routinely recommended for children on the autism spectrum. A variety of other supplemental approaches like play therapy, music therapy, art therapy and in some cases horse therapy, water therapy and horticulture therapy are also offered.

## Early Intervention Goals

However, before we go further into what these therapies are and how to choose them, it may help to stop and ask what our goals are while we put the child through these early interventions. Yes, the child is on the spectrum, yes, she has certain challenges but then, what should early intervention help the child with? Once we are clear about the goals of for the child, we can go ahead and talk about choosing interventions accordingly.

To start with, early childhood development goals for children on the spectrum are not different from the same goals for children in general. In both cases, one is looking for development along physical, social, cognitive, and emotional dimensions. However, children on the spectrum are likely to have a variety of specific challenges in these areas, and therefore, the goals are likely to be more specific. They may also find it difficult to learn these behaviors from the environment by observing and copying adults and other children, and so, may need suitably designed interventions and therapies.

### Communication Goals

Children on the spectrum tend to face challenges related to speech, language, and communication. Some children may not be able to speak at all, due to poor motor coordination and other physical and neurological difficulties. Some children may be able to produce all sounds but limit their verbal interaction to a few words and not sentences. In some cases, children may be able to produce language fluently, as in be able to speak full sentences, recite poems etc. but may not be able to use language to communicate by asking questions, making observations etc. Many children may not understand verbal inputs and instructions. Some may be able to understand but may not be able to respond. Even in cases where children are unable to speak, they may show a willingness to communicate if the speech barrier is removed. In most cases, parents manage by trying to guess what the child means or wants. As the child grows up, this does not work and the inability to communicate leads to anxiety and other difficulties. So, an important goal is to help children develop a channel for two-way communication either using speech or using other alternative forms of communication.

### Social Goals

Children on the spectrum also have a variety of social difficulties, starting with not responding when parents call their name, not being able to interact with parents. Children may not want to interact with peers or may not know how to take part in interactive games. They may behave inappropriately as they do not understand the rules of social behavior. For example, when in a play area, they may just follow other children around, copy their actions or snatch toys from others. So, teaching appropriate social behaviors and helping children cope with the demands of everyday social interactions at home, play areas and public places is another goal.

### Physical Goals

Children on the spectrum may have physical challenges, with movement and balance. For example, many children walk on their toes, or find it difficult to hold erect posture while walking. Some are not able to balance naturally and so might find it difficult to walk up and down stairs, step over small obstacles like doorsteps etc. A few children may experience significant difficulties in coordinating their movements, to the extent of not being able to move around or use their hands without assistance. Many children also present with low muscle tone and overall poor motor coordination. One of the goals of early intervention is to help children develop better motor coordination and be able to navigate their world comfortably.

### Sensory Goals

Children also present a variety of sensory challenges. Due to their neurological uniqueness, some children may have a different sensory experience than others. For example, some children are overly sensitive to the sound of a pressure cooker whistling. They may close their ears, run away, or show other unusual forms of distress around the noise. Some children find it difficult to handle different textures either to touch or to mouth. They may refuse to eat certain kinds of foods and may prefer to stick to one or two items of food. This preference might pose significant challenges when children end up eating only chicken nuggets or fruits and milk for years together. The interventions we choose need to address the sensory challenges of the child.

### Behavioral and Emotional Goals

They may also experience a variety of behavioral and emotional challenges. Many children do not like to be disturbed when they are engaged in an activity and may find it difficult to transition from one activity or physical space to another. For example, a child might go to the play area and might resist coming back home. Or she might be playing with toys and may resist moving to the dining area for lunch. Children may also appear to not understand emotions – they find it challenging to read the emotion from facial expression and body language. Young children may not have enough linguistic and cognitive ability to understand emotions in the abstract. Guiding and helping children manage these variety of challenges needs to be among the goals of early intervention.

## Key Focus

It is important to understand that the way a child experiences autism and the way it shows up through her behavior in the environment, comes from a combination of multiple factors. A child may not like the texture of food presented to her, may have a severe sensory response to it and may start feeling distressed. Now, she does not have language or other tools to communicate the same, does not understand the social behavior expected of her, and may start experiencing a serious emotional response. When a helpful adult tries to touch her, feed her, or talk to her, the added physical and verbal inputs further aggravate her distress. If she does not get help at this stage, she may resort to what is seen as ‘inappropriate behavior’ to communicate her distress. For the others around her, it looks like the child was offered tasty food, was encouraged to try out and taste it, but instead of doing what is expected, she has started closing her ears, shouting, kicking, and throwing the food around. However, the way she experiences the entire interaction is hugely different.

As we have seen above, these difficulties sometimes work together to produce profoundly difficult outcomes, and it is important to take all these areas into account while planning the goals for early intervention. The focus is to understand the variety of ways the child is distressed by the environment, trace the distress back to various difficulties the child has, and try address these difficulties, while building her skills and competencies.

## Choosing therapies

As discussed abovce, early intervention approaches need to address language and communication, social, physical, sensory, behavioral, and emotional goals. One therapy or approach is unlikely to address all these goals. Usually, a combination of behavior therapy like ABA (Applied Behavior Analysis), Speech and Language Therapy and Occupational Therapy are recommended. In addition, there are many other options like art therapy, music therapy, play therapy, animal therapy and so on. In the Indian context, there are alternatives like homeopathy, ayurveda and other traditional medicines. In addition, there are approaches like supplementary diets, medicines etc.

In this era of internet, news media and social media, each of these proven or unproven treatments are promoted through stories of success. Also, since every person's autism is unique, there is no one-size-fits-all solution to address the needs of every person on the spectrum. There is an overwhelming amount of information available, and making an informed decision becomes a challenge.

### A few guidelines

You should learn to critically evaluate the information you receive. Get information from objective sources.

+ People promoting various treatments may really want to help your child but may also have additional business motives.

+ Anyone making claims about “complete recovery” from autism or “curing” autism should be viewed with suspicion. There are no cures for autism.

+ The therapy approaches you choose should be evidence based. This means there should be enough scientific evidence that the approach works. Please remember that anecdotes are not evidence. Evidence-based practices include behavior approaches, developmental approaches like speech language therapy and occupational therapy.

+ The therapy approach or the combination of approaches you choose should be able to address all the goals mentioned above for the child. The therapy approach should enable you to get an assessment of your child’s specific needs in each of these areas and provide a comprehensive plan to progress on each of them.

+ The demands of the therapy approach should be aligned with your family’s capacity. For example, if a therapy approach needs you to spend more time with the child, you need to think of whether you can do this or not. It should also suit your financial ability.

+ Complimentary approaches involving working with art, music, movement, animals, swimming, play should be treated as complimentary therapies. These can be practiced in addition to the evidence-based early intervention approaches above.

+ Most methods of working with autism work slowly compared to the quick results one expects from medical treatments. That is the way it is. Anyone making time bound promises like “making your child school ready in six months” needs to be evaluated with caution.

+ Since there are no medicines for the core symptoms of autism, one needs to be cautious about medication as a solution. Please evaluate the medication carefully. With young children, it may be best to avoid medication except in case of severe medical conditions like seizures.

+ Extra caution is advised in using medication from ayurveda and other traditional medical systems. Most of these medications may be untested and unproven. Homeopathy may also be approached with caution – there are many controversies about whether it works at all. One of the problems with relying on unproven alternatives and medications is that these practices distract the family, divert attention from what needs to be done and may even interfere with the therapies.

+ Similarly, the efficacy of diets and supplements is at best questionable. An additional problem with restrictive diets is that children end up being deprived of many commonly consumed food items and may be nutritionally impacted. This feeling of deprivation may result in behaviors like grabbing food from others. Additionally, in the Indian culture where most social occasions revolve around food, children may also be socially impacted. While putting a child on a diet may look like an easy option, it may end up having profound consequences.

**In summary, the key to choosing a good approach is to go with one that is evidence based, addresses the development needs of the child, and suits the family circumstances.**

## Choosing a service provider

After understanding the goals of early intervention and how to choose a therapy approach comes the question of how to choose a service provider for the therapy delivery and what to expect as you start working with them. Here are some thoughts that can help.

### Multifunctional Approach
As we saw earlier, all the goals and needs of a child cannot be addressed by one therapy or approach. When working with multiple therapy providers, the parents end up having to coordinate between different therapists. In such cases, it is important to ensure the therapists are willing to work with you for this purpose. A better case would be when therapists are willing to talk to each other. The best is when a single service provider brings together the multifunctional team needed to meet all the therapy needs of your child.

### Family Centred

While it is the individual with autism that receives the therapy, it is the entire family that is dealing with autism. A service provider willing to take a family centric approach should be preferred. The service provider should understand the importance of co-opting the family, keeping them involved, and support and train them, as necessary. Parental involvement and training become especially important when young children are involved as the children may benefit more when therapists and parents understand each other and work together.

### Assessments and plans

When the therapy providers start working with your child, they should assess your child’s needs and develop an Individual Education Plan. Please ask the service providers what kinds of assessments they conduct to ensure they identify the specific needs and goals of your child. These assessments are necessary, so an individually designed therapy plan is developed for your child.  This plan should also include details of how they plan to track and communicate the progress to you. Please insist that this plan be made and shared with you in a reasonable time. It is also important that the providers explain this plan to you in a way you can understand. Ideally, this plan should include your input and requirements as well.

### Clear communication

At all points of time, the service providers should provide clear and transparent communication regarding the goals, the program, and the progress. Service providers should be willing to include parents and other caregivers in the therapy program.

### Respect and dignity
Any practice that does not respect the individual with autism and the caregivers needs to be questioned. Individuals need to be treated with dignity and respect, irrespective of the goals and efficacy of the therapy. Parents and caregivers must be treated with respect and recommendations delivered respectfully. Most importantly individuals and parents should never feel pressurized or bullied by professionals.


### Training and qualifications
Whether the therapy is provided by a single provider or by different providers, it is important for the parents to ensure that the therapists are well trained and qualified to deliver the therapy. Please do not hesitate to ask for details of certification and training.

### References and history

When choosing a service provider, please ask for references and learn about the experience of other parents who have worked with them before. Please learn about how the providers deal with children, parental questions, and concerns and what the outcomes of the therapy were.

**In summary, the therapy provider you choose should take a multifunctional approach, involve the family, provide comprehensive therapy plans and progress tracking and be respectful to the individual with autism and the family.**

## Autism, Speech and Communication

One of the key features of autism is communication challenges. These include not understanding the importance of communication, not being able or willing to communicate, not being able to communicate appropriately in social situations, etc.

In addition, an estimated 25 to 35 percent of people on the autism spectrum have little or no functional speech. Speech in autism is also along a wide spectrum, including those that speak fluently to those that do not speak at all. The usual words used in this regard are – minimally verbal for someone who uses little speech, nonverbal for someone with no speech and preverbal for young children.

Like in many areas related to autism, the current research on non-speaking autism is limited, and we do not really know what causes functional speech difficulties. A variety of causes for limited speech in autism are possible: auditory processing, the system in brain that interprets words, might be poor; there could be motor planning issues like speech apraxia that impacts peoples’ ability to plan and coordinate mouth and tongue movements; differences in brain anatomy in the speech production network can also be involved.

### Communication is not just speech

However, there is a difference between speech and communication – speech is the ability to produce words, whereas communication is the ability to convey and receive meaning. It is a misconception that children who do not speak cannot understand or communicate. It is also not true that those that can speak can automatically communicate and understand others. Also, people who do not or cannot speak do not have less intelligence scores than those who speak. They need communication as much as anyone else.

Living in a world that revolves around language, speech and communication can be particularly challenging for people on the spectrum and more so for those that do not use much speech. The current assumption is that people who cannot communicate become frustrated and that becomes a trigger for various other unhelpful behaviors. Whether it is completely true or not, there is broad agreement among experts that having a two-way communication channel is important for everyone.

### Looking beyond speech - AAC

Speech is particularly difficult for some people on the spectrum. We do not understand the reasons for these difficulties, but recognize that effective communication is important for everyone, and that speech is not the only way to communicate. It therefore makes sense to look beyond speech and enable everyone to find a channel of communication, using augmented and alternative communication (AAC) as necessary. AAC is a broad category that includes sign language, gestures, pictures, written words, and electronic devices.

This is not to say that speech is not necessary or important. Speaking and understanding spoken language can make life significantly easier for people on the spectrum and their families. However, considering the difficulties they have with communication and speech, limiting oneself to speech-only approaches can be counterproductive. It is advisable to explore the use of AAC for communication, as early as possible.

AAC can provide a communication channel for people on the spectrum who have difficulties with speech and communication. It has been shown that even with people who speak, the use of AAC can make communication more effective, by providing a necessary scaffold. Also, the common apprehension that use of AAC stops children from acquiring speech is not true, as shown by a 2021 study, among others.

**In summary, communication is a key element of working with autism and needs to be highly prioritized. People who find it difficult to speak should be supported with augmented and alternative communication as needed.**

## Video - Make it Visual - help your child understand you

In the video below, Dr. Nanditha De Souza of [Sethu](https://sethu.in) talks about how visual support help a child understand information better. Visual support is a form of AAC that helps a child communicate easily. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/1t9MU28VV6c?si=CGBeq8Xz8HpWBG-b" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Speech Therapy is not just about speech

Yes, speech therapy and speech therapists are not all about “speech.” A speech therapist is really a speech language pathologist (SLP), but they are not just about language either. The overall goal of SLPs is to help a person communicate in functional ways.

Communicating in functional ways certainly includes learning to use speech and language for communication but may also include learning to read nonverbal communication like facial expressions and gestures, learning to communicate in social situations etc. When working with people on the spectrum, the focus of SLPs is to holistically improve the ability to communicate and that may include using augmented and alternative communication (AAC).

Communication and speech related challenges vary widely from person to person on the autism spectrum. Some individuals may not be able to produce any sounds, some may be able to produce speech but may not be able to use it to communicate, and at the other end, some may be able to speak fluently yet may have difficulty sticking to a topic or communicating appropriately. Accordingly, SLPs perform a variety of functions.

### Functions of Speech Therapists

+ Prelinguistic skills – help children learn skills like eye contact, gestures, vocalizations

+ Nonverbal communication – help people learn to notice nonverbal signs in a conversation

+ Feeding interventions – some individuals tend to have difficulties with chewing, swallowing etc. Some SLPs are trained to help in these areas.

+ Assisted and Augmented Communication (AAC) - SLPs can also train people in using AACs to communicate. These may include Picture Exchange Communication System (PECS), sign language or electronic devices.

+ Speech fluency – SLPs can help people on the spectrum with speech clarity, and fluency.

+ Articulation – Speech requires coordination of different structures. SLPs can help improve the 	muscle strength, coordination and manipulation needed to produce speech.

+ Grammar – many children on the spectrum struggle with grammar and sentence structure. SLPs can help them understand language

+ Functional Speech – echolalia, repetition of sounds, words and phrases is a common coping mechanism. SLPs can help in building functional speech.

+ Social skills – SLPs can help coach people on the spectrum to communicate in different settings, either in one-to-one sessions or group sessions.

+ Social communication – SLPs can help children use language for different purposes like demanding, informing, commenting.

+ Transition to work – SLPs can also continue to help as the individual transitions to a work environment by coaching how to communicate in written and spoken forms.

When working with an individual on the autism spectrum, SLPs assess strengths and challenges and develop a program with goals for the person and the approaches to achieve them. This program then becomes the basis for working together and assessing the effectiveness of the therapy.

Parents of children on the spectrum should understand that the goal of the SLP is to facilitate communication and be willing to prioritize functional communication. **A two-way channel of communication is the most important need of a child on the spectrum.**

### Choosing an SLP

* SLP is an important member of the team of experts working with your child. Choose someone whose program matches your priorities and goals.

* Remember that functional communication is the priority, over speech or being able to repeat rhymes or learning alphabet.

* Ensure the SLP is willing to work with other experts either directly or through you.

* Work towards building transparency in your relationship with the SLP. You should know what is happening in the session and be trained to carry out some interventions at home, as needed.

* Choose someone who can help with AAC as needed, training you, the child and others who interact with the child.

**In summary, speech therapy is not just about speech or language but about holistic communication. A speech therapist is an important member of the team working with your child and should be chosen carefully to align with the child’s goals and requirements.**

## Occupational Therapy

May people on the autism spectrum face motor difficulties. They may have gross motor difficulties, such as a clumsy way of walking or difficulty with large motor movements or difficulties with fine motor skills like writing, coloring in the line or using scissors. Some may have trouble coordinating movements between the right and left sides of the body making it difficult to skip, jump, hop or get down the stairs. Some others may have trouble with hand-eye coordination making it difficult to catch a ball, hit a ball with a bat etc.

In addition to these motor difficulties, children on the spectrum may also struggle with low muscle tone, sensory processing issues (too much or too little response to sensory inputs such as sound, touch, smell etc.), as well as difficulties with proprioception and interoception.

It has been estimated in a 2020 study conducted in the US that as many as 87% of children between 5 and 15 years of age on the spectrum face motor difficulties. Yet, only about 30% of the children were receiving any therapy for the same.

Motor issues may appear in infancy where 1-month old infants who are later diagnosed with autism move their arms less, they may struggle to keep their head in line with shoulders when pulled up to sit at 4 months and may struggle to stand at 14 months.

Poor motor skills may contribute to and accentuate autism traits as motor issues can delay babbling, gesturing, and acquisition of new vocabulary. Lack of motor skills may also elicit less interaction from caregivers and provide children less prompts for learning.  Poor motor skills later in childhood may make children on the spectrum reluctant to participate in physical activities, limiting opportunities for social interaction. Bad handwriting can impact academic performance. Since visual-motor integration skills are important for imitation and learning from others, lack of these skills can hamper social development. Thus, motor difficulties might have cascading effects on cognitive, social, and emotional development.

That is why occupational Therapy is among the top therapies recommended for autism. The general focus of occupational therapy is to improve the client’s ability to participate in activities of daily living, which may include things like schoolwork to dressing and brushing teeth.

When an occupational therapist starts working with a child, they usually assess their support needs. They may use some tests like the school function assessment test (SFA), Children’s Assessment of Participation and Enjoyment/Preference for Activities of Children (CAPE/PAC), Assessment of Life Habits (Life-H), Children Movement Assessment Battery for Children Second Edition (Movement ABC2), Sensory Integration and Praxis Test (SIPT) etc. In addition, the therapist may observe the child in a range of settings to see if they are able to complete tasks of daily living. For example, they may watch to see if a child can button a jacket, cut with scissors, play appropriately in the playground, etc.

Once the tests and observations are complete, they develop an individual plan for the child. The plan is personal and may include academic goals like using scissors, printing letters, using a paint brush; daily living skills like brushing teeth, zipping jacket, tying shoes; social functioning goals like catching a ball, jumping on trampoline etc.

Occupational therapists usually work with the children in occupational therapy rooms or sensory rooms equipped with exercise balls, swings, jump ropes and other equipment. Therapists use techniques to strengthen the child’s hands, legs, and core, provide tools like weighted vests or large pencils to make some tasks easier etc.

The role of occupational therapists is not limited to working with children. They may work with adults to build living skills like cooking, cleaning etc. They may help with designing more comfortable workstations and equipment for adults working in offices. They can help in various areas of self-care, productivity, and leisure.

### Sensory Processing and Occupational Therapy

We rely on the information coming from our senses (sight, sound, smell, touch, taste) to make sense of the environment around us. People on the autism spectrum may have difficulties dealing with the information coming in from different senses. A child may be distracted by the noise of a drill that you can barely hear. Another child may be feeling uncomfortable with the shirt label scratching on their neck. Yet another child might be getting overwhelmed with the perfume in the air. Too much sensory information can cause stress, anxiety, and physical pain. This can result in withdrawal, distressed behavior, or meltdowns.

### Different sensory profiles

People on the autism spectrum can be under sensitive, oversensitive or both (at separate times) to any of their senses. For example, people who are under sensitive to sight may not have a good depth perception and may not be able to catch or throw. Those who are oversensitive may find it difficult to sleep even with a little light around. People who are under sensitive to sound may prefer crowded, noisy places or bang doors and objects. Those that are oversensitive to sound may not be able to filter our background noises, leading to difficulties in concentrating. People under sensitive to smell may sometimes lick things to get a better sense. Those that are oversensitive may have difficulties using toilets or may dislike people with distinctive, strong perfumes. People under sensitive to taste may like very spicy food. They may also eat or mouth non-edible items such as stones, dirt, soil, feces etc. This is known as pica. People with sensitivities to taste may end up with a restrictive diet. People under sensitive to touch may hold others tightly, enjoy heavy objects like weighted blankets on top of them. They may have a high pain tolerance and may self-harm. Those oversensitive to touch may not like to be touched and may have difficulties brushing and washing hair. They may also tolerate only certain types of clothing or textures.

### Working with sensory processing

In general, people who are under sensitive to a sense seek out more of that sensory input to calm themselves, to relieve anxiety and sometime just for pleasure and relaxation. Those that are oversensitive try to avoid that sensory input for the fear of being overwhelmed. People on the spectrum may need help in handling these sensitivities. The general approach is to provide manageable alternatives to the under sensitive system and to slowly desensitize the oversensitive system through gradual exposure. For example, if a child is easily overwhelmed by sounds, she may close her ears every time someone speaks to her, losing out on useful information and learning opportunities. The therapy approach in this case would be to offer her earmuffs that can decrease the intensity of the noise, couple the sound input with a visual and gradually help the child be comfortable with the sound of spoken voice. A child who is under sensitive to touch may keep scratching walls or rough surfaces for stimulation, causing injury to fingers and nails in the process. In this case, the therapist may offer a manageable alternative by giving her a polystyrene sheet to scratch and get the sensory input.

### Sensory Integration Therapy

Occupational therapists trained in dealing with sensory processing difficulties can help by providing interventions to target each sense, helping the child’s nervous system become more organized and regulated. Sensory integration therapy is one of the names given to such an approach. One of the options is to put a child on a sensory diet, a specially designed daily activity plan that provides the child with a variety of sensory activities. The focus is to help the child be regulated and improve attention and focus. When the child’s arousal level is too low, they can be given stimulating activities like dancing, singing, light exercise etc. When the arousal level is high, they can be given calming activities like going for a walk, reading, listening to music etc. It is important to choose activities that suit each child and provide the appropriate level of arousal or relaxation.

### Sensory Circuits

Sensory circuits are another tool used by therapists to help children achieve a ready-to-learn state. Each session includes three elements.

+ Alerting activities to stimulate the body's central nervous system in preparation for learning. For example, spinning, bouncing on a gym ball, skipping, star jumps

+ Organizing activities which demand brain and body to work together. For example, balancing on a wobble board, log rolling, juggling

+ Calming activities give an awareness of their body in space and increase the ability to self-regulate sensory input. For example, heavy muscle work and deep pressure like wall pushes, pushups, using weights.

**In summary, some people on the spectrum may have sensory processing difficulties that make it difficult for them to process sensory information. Occupational therapists trained in sensory integration can help by designing sensory diets and other programs that can help children be more regulated, calmer, and focused, thereby reducing anxiety and increasing opportunities to thrive and achieve in the overwhelming environment in which we now live.**

## Beyond the five senses

We are all familiar with the five senses – sight, sound, touch, smell, and taste. However, there are three other senses that are not as well known. In the context of autism, it is important to know about these senses as people on the spectrum tend to experience processing difficulties related to these senses as well.

The three other senses are – Proprioception, Interoception and Vestibular system. Proprioception is our body’s intrinsic ability to sense and position itself in space. We have a set of sensory receptors in our muscles, joints, and tendons, that help us with full-body awareness. Interoception is our ability to sense our internal body states and emotional states, using the information we receive from receptors on our internal organs. The vestibular system is in our inner ear and helps us with our sense of balance and body control.

### Proprioception

People on the spectrum can have proprioceptive difficulties that make it difficult for them to apply the right amount of pressure for a task. They also bump into things often and may have difficulties walking up and down stairs. They may struggle while feeding themselves, and frequently miss the mouth. They may also struggle with posture and movement fluidity when faced with a new motor task. They may underperform in sports and may struggle to remember the body posture associated with a new skill.

Proprioception difficulties can be addressed by occupational therapists using sensory integration techniques and practicing gross and fine motor movements with visual assistance like looking into a mirror while performing a task.

### Interoception

Regarding interoception, people on the spectrum may be less aware of what is happening inside their bodies. The interoception center in our brains is called the insular cortex, which also plays a vital role in the perception of pain, primary emotions like joy, anger, awareness of bodily states like feeling of cold, and in the perception of being a self. Therefore, interoception difficulties may be responsible for emotional processing issues, problems in identifying and describing emotions, and difficulty with empathy and perspective taking. At an extremely basic level, people on the spectrum may not be able to recognize when they are thirsty, or hungry. They may not realize when they are full and may tend to overeat. They may find it difficult to self-regulate their emotions, attention, and behaviors. They may not be able to point to the source of their discomfort like where the pain is.

Interoception can be improved by practicing interoception awareness activities like guided self-body scans, deep breathing, guided progressive relaxation. Young children may need support with the help of timers for eating, drinking and toileting, portion control to help eat for balanced nutrition etc.

### Vestibular system

The vestibular system refers to the structures in the inner ear that detect movement and change in the position of the head. This is the system that tells us if our head is upright or tilted, even with our eyes closed. Children who are oversensitive to this system can have fearful responses to ordinary movement activities like swings, slides, ramps etc. They may appear clumsy and fearful of moving in space. However, some children may actively seek intense sensory experiences such as excessive whirling, jumping, climbing heights, etc. Vestibular dysfunction can cause postural instability, gait dysfunction and impaired gaze. This can lead to delayed milestones such as sitting and walking and poor motor coordination. Vestibular dysfunction may be accompanied by auditory sensitivity and dysfunction.

Repetitive actions like mild rocking can help calm down an over stimulated vestibular system. Providing structured activities that satisfy an under sensitive system seeking stimulation can also help.

In summary, the sensory processing disorder, and related difficulties in autism go beyond the five better known senses and may impact proprioception, interoception and vestibular system. The impact of these dysfunctions is still being researched and understood. An occupational therapist can provide sensory integration therapy to help with these difficulties.

