---
format:
  html:
    include-after-body:
       - "_includes/load-comments.html"
---

# Identification and Causes

Autism is a neurodevelopmental variation. The most effective way to support autistic people is through understanding, acceptance, and providing individualized supports and accommodations. Early identification can help families and communities better understand and support autistic individuals.

However, autism is a spectrum condition, so the symptoms may vary in type and severity from child to child. In addition, since each child develops in his/her own way, some early signs of autism look like they are part of the natural development of the child. Also, Indian families often tend to think that speaking a little late, being a little unresponsive, is nothing to worry about. One often hears things like "oh, his father spoke at three, look he is all fine now!" and "boys start speaking late anyway".

All of this makes early identification and action difficult for parents. Other family members and friends tend to keep their peace till the child is older. Most medical professionals may also advise a wait and watch approach.

While autism can look different in different children, the most common areas of difference are communication and interaction with others. Signs of autism can be noticed when the children are around 2-3 years of age or even earlier. Parents and caregivers may watch for these signs.

## Identification

When you notice any of the following signs in the children around you, it is useful to consult a developmental psychologist or a developmental pediatrician at the earliest. It is possible that these signs do not mean autism, but if they do, then you would have recognized these differences a little earlier and started providing support, thereby helping the child access resources and understanding sooner.

### Differences in reaching developmental milestones

 Autistic children may show some early signs of being on the spectrum, such as reaching developmental milestones on their own timeline or engaging differently with their environment (these vary for each child).

+ Does not respond to name by 9 months of age
+ Does not show facial expressions like happy, sad, angry, and surprised by 9 months of age
+ Does not play simple interactive games like pat-a-cake by 12 months of age
+ Uses few or no gestures by 12 months of age (for example, does not wave goodbye)
+ Does not share interests with others by 15 months of age (for example, shows you an object that they   like)
+ Does not point to show you something interesting by 18 months of age
+ Does not notice when others are hurt or upset by 24 months of age
+ Does not notice other children and join them in play by 36 months of age
+ Does not pretend to be something else, like a teacher or superhero, during play by 48 months of age
+ Does not sing, dance, or act for you by 60 months of age

### Communication differences

About 40% of autistic children do not use spoken language, and between 25% and 30% develop some language skills during infancy but then communicate differently as they grow. Some autistic children start using spoken language later in life, or may use alternative forms of communication.

Many autistic children communicate in ways that differ from neurotypical expectations, including:

+ Does not give or sustain eye contact
+ Delayed speech and language skills
+ Flat, robotic speaking voice, or singsong voice
+ Echolalia (repeating the same phrase over and over)
+ Reversal of pronouns (saying “you” instead of “I,” for example)
+ Not using or rarely using common gestures (pointing or waving), and not responding to them
+ Does not stay on topic when talking or answering questions
+ Not recognizing sarcasm or joking
+ Trouble expressing needs and emotions
+ Not getting signals from body language, tone of voice, and expressions

### Repetitive behaviors and focused interests

Autistic people may have unique ways of engaging with the world, such as focusing deeply on particular interests or using repetitive movements to self-regulate. 

Examples of repetitive behaviors and focused interests that are common among autistic people can include:

+ Lines up toys or other objects and gets upset when order is changed
+ Plays with toys the same way every time
+ Is focused on parts of objects (for example, wheels)
+ Has strong preference for routines
+ Has focused interests
+ Flaps hands, rocks body, or spins self in circles
+ Has unusual reactions to the way things sound, smell, taste, look, or feel
+ Has strong likes and dislikes with respect to food 
+ Differences in coordination and movement 
+ Acting quickly or impulsively 
+ Expressing distress through strong emotions or actions
+ Varied attention spans

### Other Characteristics

Many autistic people may also experience other characteristics, such as:

+ Differences in cognitive or learning skills
+ Hyperactive, impulsive, and/or inattentive behavior
+ Co-occuring conditions like Epilepsy or seizure disorder
+ Unique eating and sleeping habits
+ Gastrointestinal issues (for example, constipation)
+ Distinct emotional reactions
+ Experiences of anxiety, stress, or excessive worry
+ Differences in experiencing and expressing fear

Autistic people often have unique strengths, such as deep focus, creativity, attention to detail, and passionate interests. Recognizing and valuing these qualities helps build a more inclusive and supportive community.

## How common is autism?

When parents are told that their child has or is at risk of autism, their first reaction is shock and then disbelief. They often think “how can this happen to us?” and then go on to “why is this happening to us?” Most people spend about six months to one year trying to make sense of it. They try to rationalize the symptoms; they hope the diagnosis is not correct and that the child will achieve the milestones in another year and things will then be alright.

People seem to believe autism is a rare condition and most people haven't heard of it before. However, the actual prevalence numbers tell a different story. The highest prevalence numbers come from the Autism and Developmental Disabilities Monitoring (ADDM) Network of the Center for Disease Control (CDC) in the US. According to their 2020 estimates, 1 in 36 children aged 8 were on the autism spectrum - that is about 3 children per hundred. In the same year, CDC estimated the prevalence of autism in adults at about 2.21% - that is about 2 persons per hundred. The World Health Organization has a lower estimate of about 1 in 100 worldwide, based on a review of about 71 studies across the world from 2012-21.

The prevalence numbers for India are not reliably available but the scientific community agrees that the biochemical pathways involved in core autism are unlikely to be different in different populations. This means that the prevalence of autism in India is likely to be closer to the worldwide estimates of about 1 to 3 people per hundred. This means about 1.3 - 1.5 crores of people on the autism spectrum, which is very significant.

What do these prevalence numbers mean? It means we need more awareness about autism because it is not as rare as people believe. We need more awareness in new parents and to-be parents so we are all better prepared. It means we need more facilities, resources and a coordinated action plan for autism in place of the current status where the responsibility is with individual parents.

There is another thing that comes to mind - World Health Organization estimates about 1 in 6 people across the world experience a ‘significant disability’ - that is about 16% of the population, numbering about 1.3 billion people. CDC also reports that about 1 in 6 (16%) children aged 3-17 years were diagnosed with a developmental disability in the study period of 2009-17. However, those of us who do not have any disability continue to believe that disabilities are rare, we ignore how common they are and continue to build a world that excludes those with disabilities. That way, people living with disabilities are one of the largest voiceless minorities in the world.

In such a world, it is no wonder that people go on without awareness of the incidence of disabilities, they are not educated about the possibility of a disability in their children, and are shocked and surprised when something like autism shows up at their doorstep.

These prevalence numbers should make us all aware of the size of the issue, jolt us out of the ignorance and get us started on the path of building more awareness, being more empathetic and inclusive in our daily lives. Listening to autistic people and including their perspectives in conversations about autism is vital for creating supportive and respectful environments.

## What causes autism?

Most families first respond emotionally when they are told that their child is on the autism spectrum. Some go through denial; others are sad or furious. Soon, emotions give way to questions and one of these questions is - “What caused my child’s autism?” Parents often ask themselves what they could have done differently. Another thought is that if we know what causes autism, maybe we can “cure” it. Some parents also ask this question as they plan to have another child and wonder about the risk of the other child also having autism.

The truth is, we do not really know the specific causes of autism. Therefore, it follows that there is no way any parent could have done anything different so their child would not have had autism. Also, since autism is a natural variation in neurodevelopment, currently there is no way to “cure” it. However, the information we have from current studies indicates that if one child in a family is autistic, there is a higher chance of having another autisitc child.

::: {.callout-note appearance="minimal"}
What we know about causes of autism is that there are a variety of factors - “a spectrum of causes” - behind the occurrence of autism, including genetic and environmental factors.
:::

### Genetic Factors

Genetics plays a large role in the incidence of autism, as evidenced by a 2019 study of more than 2 million people across five countries, which estimated ASD’s heritability to be approximately 80%.

The role of genetics is also indicated by the concordance rate (both of two siblings having autism). In siblings, who share 50% of their genes, the occurrence of autism in both the siblings (the concordance rate) is 20%. Similarly, in fraternal twins, who share 50% of genes and grow in the same womb, the concordance rate is 31%. However, genetics are not the only causal factor - this is evidenced by the concordance rate of 77% even in identical twins, who share 100% of their genes, and grow in the same womb.

Here is a TED talk by Wendy Chung where she talks about genetic factors in autism.

{{< video https://www.youtube.com/embed/wKlMcLTqRLs?si=FU5z2Jgf68XVavao >}}


Genetics play a large role does not mean autism runs in the family. Certain individuals have it brand new because of mutations in the sperm or egg at the time of conception which are not passed down. Also, while we know genetics play a large role, the current studies do not provide information on what genes are involved, or even if it is a combination of genes. Furthermore, A study by Simons Foundation found that the genetic changes/ alterations were different for different individuals even among a population of 2600 that had brand new autism - this means there is not 1 gene, but about 300-400 genes (that are not random, but fit together in a pathway/ network) causing autism - possibly why there is such a wide spectrum of autism.

### Environmental Factors

A variety of environmental factors have been examined for their contribution to autism. While there are studies that have found correlation between some environmental factors and the incidence of autism, it is important to note that the research is in early stages. The evidence for some of these factors is strong and for some, it is confusing or weak. While we know some of these factors play a role, we do not know how exactly how that role works. In addition, some factors like air pollution are so generic and so widespread that there is little anyone can do about them. So, while we know in general that there are a variety of environmental factors, we do not have a single, actionable, point that can make a significant difference.

Some of the environmental factors that have a strong to moderate current evidence are:

+ the use of certain medications during pregnancy - Valproic acid (given for epilepsy), Selective Serotonin Reuptake Inhibitors (Used to treat depression)
+ extremely preterm birth and low birth weight
+ Older parental age at the time of conception
+ Bacterial and viral infections in the mother while pregnant
+ Maternal autoimmunity

As of now, we do not exactly know what causes autism. There is much research being conducted on both genetic and environmental causes and the early results are promising. However, if a family has a child on the spectrum now, it might be more important to ask what can help the child rather than what causes autism, since the second question is unlikely to be answered in the near future in a definite way that can change the current ways of supporting autism.

## Do vaccines cause autism? {#sec-vaccines}

If you are remotely connected to autism, it is highly likely you have come across this question before. The answer is, no, vaccines do not cause autism. This theory was proposed in 1998, has been thoroughly investigated and conclusively proven to be false by 2010.
What contributes to its widespread popularity and longevity?

### Origin of the vaccine connection
In 1998, a physician by the name Andrew Wakefield made this claim in a paper published in the medical journal Lancet. During that time, the two most popular candidates for the cause of autism were refrigerator parenting and genetics/neurobiology. Wakefield looked at 12 children who were developing normally until the administration of the Measles, Mumps, and Rubella (MMR) vaccine and started exhibiting autistic symptoms shortly after. He believed that the vaccine affected the large intestine and assumed that neurotoxic proteins released through the intestine reached the bloodstream and brain, causing autism. His belief was strengthened when all the children he performed colonoscopies on exhibited the lesions.

The theory made sense as autism symptoms in children started to appear around the same time as the vaccine administration i.e. 12 to15 months of age. “It was after the vaccine that my child stopped talking/ started behaving this way” is a common refrain one hears even today. The theory also gained popularity with parents as it took away the burden of blame from them. Autism cases were increasing rapidly, people were looking for a cause, and this plausible theory gained credence.

### Debunking the theory

The vaccine link looked obvious and was convenient but other researchers were unable to replicate the findings. Also, considering the diversity of how autism presents itself, a common biological cause looked unlikely to the scientists. In 2005, an investigative reporter alerted the editors at Lancet that Wakefield's study had been flawed by severe research misconduct, conflict of interests, and falsehood.

After investigating the matter, Lancet retracted the article, and the British Medical Association took disciplinary actions against Wakefield. Since then, any direct connection between autism and the MMR vaccine has been discredited by dozens of studies investigating the roots of autism and the biological effects of MMR and the mumps virus. Also, even as more parents were opting out of MMR vaccination, the rates of autism had been rising.

Soon after, there was a suspicion about another autism-vaccine link. It was suspected that thimerosal, added to vaccines as a preservative, could cause autism. Thimerosal contains mercury, a poison, but there was no evidence that the small amount was harmful.  To see if thimerosal was linked to autism, researchers studied children who received vaccines that contained it. They compared them to kids who received vaccines that did not contain thimerosal and did not find significant differences in the rates of autism. Even then, thimerosal was taken out of most vaccines.

::: {.callout-note appearance="minimal"}
Since 2003, there have been nine studies funded or conducted by CDC (Center for Disease Control) that have found no link between thimerosal-containing vaccines and ASD (autism spectrum disorder). These studies also found no link between the MMR vaccine and ASD in children.
:::

Researchers have also looked to see if all the vaccines required before age 2 together somehow triggered autism. Children receive 25 shots in the first 15 months of life. Some people feared that getting all those shots so early in life could lead to the development of autism but there is no evidence that this is true. The CDC compared groups of children who received vaccines on the recommended schedule and those whose vaccines were delayed or did not get them at all. There was no difference in the autism rate between these groups.

Thus, through these several scientific studies, it has been concluded that there is no evident link between vaccines and autism.

## Timeline of Causes of Autism

1949 - Kanner proclaims his theory that autism is caused by "refrigerator mother", a term used to describe parents who are cold and detached.

1964 - Refrigerator mother theory challenged with possible neurological factors (Rimland)

1967 - Refrigerator mother theory reinforced through the “Empty Fortress” book

1977 - First study of twins and autism- Genetics as important risk factor

1998 - Andrew Wakefield claims MMR Vaccine triggers autism

2010 - Andrew Wakefield’s paper retracted, barred from practicing medicine, and loses medical license.

Autism research continues and so far, scientists have identified around 100 different genes and certain environmental factors that could contribute to the possibility of autism.

## What does not cause autism?

There are a lot of misconceptions around autism. Very often parents are blamed, or parents go ahead and blame themselves for the child’s autism. They may think that their parenting is responsible for the child’s autism or in the Indian context, they are likely to blame it on themselves and their bad ‘karma.’ This blame and guilt often push the parents into denial about the child’s autism or into depression believing there is something wrong with themselves. All of this is unnecessary and is only likely to waste precious time that can be better spent on working with children.

Similarly, some parents believe that the child’s autism is not really autism, but a set of mild symptoms caused either by too much screen time, or due to lack of social interaction in nuclear families, or because the child has spent time around other children who have autism. Under this belief and the fear of the burden of autism, parents again waste precious time trying to take temporary measures like sending the child to a school to increase social interaction, leaving the children with grandparents, sending them to preschool etc.

As we understand, autism research is still young, and we do not have a complete understanding of what exactly causes autism. As of now, what is clear is that a combination of several factors (genetics, parental age at the time of conception, other environmental factors- link to “what causes autism”) may cause autism and we have some clarity on what does not cause autism. The following are some factors that were identified as “causes of autism” earlier but have been ruled out through thorough research.

### Bad parenting
It was once believed that “refrigerator mothers” meaning cold, uncaring, and emotionally unavailable mothers caused autism in children. Later, by the early 1970s, this cause was studied further, and the theory of refrigerator mothers was disproved.

### Vaccines

One of the most prevalent myths among causes of autism is that vaccines, especially the Measle, Mumps, and Rubella (MMR) and the mercury containing vaccines cause autism. This claim has been investigated thoroughly and no link between vaccines and autism has been found. See @sec-vaccines for more.

### Screen time

It has been noticed that some children develop autism-like symptoms due to increased screen exposure before 3 years of age. Some studies suggest that increased screen time is associated with melanopsin-expressing neurons and decreasing gamma-aminobutyric acid (GABA) neurotransmitter, and thus results in deviant behavior, decreased cognitive, and language development. This has been termed virtual autism.

While the symptoms are similar, and virtual autism may be diagnosed as autism, these are two different conditions. Autism spectrum disorder (ASD) is a neurodevelopmental condition with genetic links and is thus present lifelong. On the other hand, virtual autism has a definite cause, which is excessive screen exposure at an early age/ Intensive Early Screen Exposure and unlike ASD, can be reversed if intervened at the right time and with the right corrective measures.

There is no evidence that the autism spectrum disorder is caused by excessive screen time.

### Lack of social interaction

For children on the spectrum, social interaction is a difficulty. They do not intuitively know how to socialize appropriately and may not always have a pleasant experience socializing. However, this is a symptom of autism and not a cause. Children on the spectrum retain their autism, irrespective of the social exposure they get in childhood.

Social exposure may desensitize them to social situations but will not take away the autism from them. Thus, lack of social interaction may deprive the child from learning appropriate social skills but does not necessarily cause their autism.

### Interaction with people on the spectrum

Some of us believe that if a child is spending time with a child on the spectrum, they may catch autism. But autism does not work like the flu. As we have discussed before, autism is neurodevelopmental and has genetic links. If a child is getting a diagnosis, it is because the child has always had autism. It may be diagnosed late due to various other factors (denial from parents, symptoms being masked etc.) Your child is not diagnosed with autism because he/she was spending time with another child who has autism.

In summary, some popular beliefs, or apprehensions about the cause of autism have been conclusively proved to be wrong and an awareness of these can help parents focus their time and energy on more useful approaches to dealing with their children’s autism.
