---
format:
  html:
    include-after-body:
       - "_includes/load-comments.html"
---

# About the guide


This guide deals with autism and various aspects of living with it in India. Our aim is to make reliable and current information available in one place, in an accessible form. The work on this guide started in 2023 and it is up to date so far.

## People and Organizations behind this guide

The idea of a comprehensive guide for special needs populations in India started out as a shared thought between Azim Premji Foundation and a few partners working in special needs space. [Farmhill Learning Community](https://farmhill.in) has been involved in the ideation and design, and is currently responsible for creating and maintaining this guide to autism.

At farmhill, we have been working with autism for about 15 years. Through farmhill education trust, we have been running [sambhavam](https://sambhavam-autism.com/), an early intervention center, [Farm Hill Learning](https://farmhill-learning.org/), a neurodiverse, close to nature, learning community as well as [subodha](https://subodha.farmhill.in/), a homeschool support center. This guide has evolved largely out of our experience living with autism, and working with people on the spectrum and their families.

We are also glad to have access to the resources and thinking developed over the years at [Action for Autism](https://autism-india.org/) a not for profit organization that pioneered the autism movement in South Asia; [ummeed](https://www.ummeed.org/), founded in 2001 by Dr Vibha Krishnamurthy, one of India’s first developmental pediatricians, as a not-for-profit organization with the vision of helping children with and at risk of developmental disabilities reach their full potential and be included in society; and [sethu](https://sethu.in/), a charitable trust based in Goa, which helps children get the best out of their lives as they grow and develop. Between them, we have the support of the best organizations working in the autism space in India.

We are thankful to [Azim Premji Foundation](https://azimpremjifoundation.org/) for the support at various levels. This guide would not have seen the light of the day without the involvement and unstinting support of highly dedicated people at APF.

While we have the support of wonderful organizations, and the community at farm hill, the key people actively working to put this guide here are - [venu GVGK](https://gvgk.in), Chithra Seshadri and the team comprising Nethra Parthiban, Nandana U, Ishita and Chandu. Needless to say, all the errors are ours.

You can contact us by email directly on venu.gvgk@gmail.com.

## Structure of the guide and navigation

We start with an overview of autism outlining the entire autism life cycle as a precursor. The rest of the guide elaborates on the points of view presented in this section.

Next, we outline a history of autism, starting from early definitions and trace the path down to various developments in understanding and dealing with autism. This section would be of interest to those who want to understand the origins of various thoughts and perspectives associated with autism.

Then we discuss how to identify autism, how common it is, what causes and what does not cause autism. We address the vaccine question (no, there is no evidence), and also present a brief timeline of various causes of autism - most of which have proven to be wrong or of limited understanding.

In the next section, we present perspectives of people living with autism, including people on the spectrum, families living with autism, medical professionals, and social workers. We attempt to cover the life cycle of autism by including perspectives from different groups.

Then we address the diagnosis process starting from the need to diagnosis to the actual process of getting a diagnosis. We also include diagnosis for older people.

In the next two sections, we outline the immediate steps a family can take when they receive a diagnosis and proceed to explore various approaches to early intervention.

We then strike a cautionary note as we talk about alternative approaches to autism that are consider ineffective and sometimes, dangerous. This is done to ensure we provide all the necessary information.

Then we proceed to education and schooling, where we examine the goals and approaches to education and schooling in the Indian context.

The next section covers employment where we outline how people on the spectrum can train for work. We also provide some resources that can help them find and keep work.

The final section deals with being an adult on the spectrum.

## Evolving nature of the guide

This might be a good place to say that by nature, a guide to autism is an evolving endeavor, as our understanding of autism is getting better by the day. We are doing our best to keep this as up-to-date as possible, and for us, this is a labor of love. If you have any specific inputs or want to be a part of this effort, please write to us.

Thank you!