# Just Diagnosed - Next Steps
So your child is just diagnosed with autism. 

First, convince yourself of the diagnosis. Take a second opinion or third opinion as necessary. Meet other parents. This is because if you are unsure of the diagnosis, you will be unsure of what to do and that will waste time. Try and understand the rationale for the diagnosis and the recommendations. 

Second, recognise that you need help both in terms of expertise about autism and your own emotional health. You are most likely to be someone who does not know about autism. This diagnosis has come as a shock to you. You need help to make sense of it. Find support groups. Seek the help of experts, other parents, counsellors or family members. Remember that your child needs you in good shape. 

Then, recognise that the child needs help. A child with autism has a different neurology than you. She may have sensory experiences that are very overwhelming. She might be struggling with social situations, and may have communication problems. While it might be difficult for neurotypical people to imagine these problems and their severity, these difficulties are real. Traditional parenting approaches may actually make it more difficult for the child. Also, every person on the spectrum has slightly different difficulties and experiences life differently. It is important for you as a parent to learn more autism, how it is impacting your child and then help her. 

As you go ahead and make further decisions, remember that the objective is to help the child. The child needs help with sensory experiences, social issues and communication, at the very minimum. Every decision you make should be examined in the light of this question - how is this likely to help the child? 

Look for more information to make sense of autism and what your child is going through - If you are already on this resource page, you have made a start! 

Usually, the recommendation from developmental psychologists is to start therapies. Check the therapy centres around you. Examine their credentials and choose a good therapist. Here is a note on how to choose therapists. Once again, think about their recommendations and how they are going to help your child. 

While the therapies and the amount of help your child needs may look overwhelming at first,  a lot can be done using common sense. Think of how you can skill yourself up. What can you do at your end? In the Indian context, most institutions that deal with children - preschools, schools, activity centres etc. - do not have much understanding of the needs of children on the spectrum. Remember that you cannot help other people working with the child unless you have a good sense of your child, her difficulties and how to respond to them. 

All of this is going to require your time. Plan such that you are able to spend time with the child, interface with therapists and gradually develop an understanding of how to help her manage her daily life. 

In summary, take care of yourself, understand your child and continue working. You can do this. 








