---
format:
  html:
    include-after-body:
       - "_includes/load-comments.html"
---

# Perspectives - Parents of teenagers in a community learning space

The following are the perspectives gathered from four sets of parents whose children are in their pre-teens/early teens. 

All the four sets of parents and children are part of a community learning space, some full time and some part time, where they work together in groups, with other mothers and children on the spectrum. They have help from experts in behavior intervention and teaching learning processes. The following are their profiles and responses to some of the questions that we asked. These are gathered from in-person interviews conducted in June-July 2024. 

## Profiles
S-Ish
S is trained as a doctor and a dancer. Her 12 year old son Ish is interested in food and shows interest in doing academic work. He works at 3rd grade level now. He is verbal, and can ask for what he wants. He has a routine of dancing, exercise and regular physical and cognitive engagement. Ish was diagnosed at 3 and went through systematic early intervention till 9 before entering a community learning space. 

H-M 
H is a microbiologist and a teacher. Her 13 year old son M is partially verbal and uses AVAZ to communicate. H trained as a therapist for 3 years along with M while he took his early intervention and continues to work as an expert mentor. M was diagnosed when he was 3 years old, went through systematic early intervention, and joined a community learning space. While he is independent with his daily living, he needs someone to be constantly with him to take care of his safety around the kitchen and on the roads. M enjoys nature. 

S-S 
S is a housewife married to a doctor and are parents of 3 sons. The oldest being 14 years old, the second, S being 11 years old and on the spectrum and the youngest, 4 years old. S was 2 when he was diagnosed. They stayed in the US until the youngest son’s birth and till they could find stable help for S back in India. S is verbal and can communicate his likes and dislikes. He often does so with Disney characters. S knows disney movie lines by heart.

S-G 
S is a nurse, lecturer and a teacher. Her son, G is close to 13 years old and is partially verbal. He was diagnosed when he was 1 year 7 months. He went through special education early intervention along with speech and occupational therapy. He started Applied Behavior Analysis (ABA) Therapy when he was 6 years old, has been using AVAZ since he was 6.5 years old and can now communicate anything that he wants through the app. S has undergone parent training and also trained to be a Registered Behavior Technician (RBT) while G was taking ABA therapy. They are now a part of a homeschooling group where the parent and child participate in the teaching learning process under the guidance of experts. G loves listening to music.

##  Early signs and diagnosis

What were some early signs or behaviors that made you think your child might be different? What prompted you to seek a diagnosis for your child?

S-Ish - Ish always used to cry. I thought it was usual for babies to cry and always just tried to stop his crying. He didn’t feel different at all. I left him under the care of my mother and went to continue my masters. My mother felt it was difficult to deal with him. He wouldn’t communicate much but we assumed he could be a late speaker. Despite our medical background, we couldn’t pick up on the signs until we went for a friend's get together and a pediatrician friend saw him and suggested we go for a diagnosis from a clinical psychologist. The appointment was 2 days away. So, I started reading up about Autism and realized that Ish was ticking off almost everything on the checklist. I could relate with all the symptoms. He was 2 years and 6 months old then. He was diagnosed with Pervasive Developmental Disorder, not otherwise specified (PDD, NOS) at that point.

HM - M had evident milestone delays by 5 months of age. He wasn’t sucking, there was no neck control, no eye contact or any non-verbal communication. We were noticing the signs until he was 1 year old but could not understand what or why. He was 1.5 years old and there was no speech yet. Until then we were doubtful. We were also scared that if we go get it checked, there might be something wrong. We were convincing ourselves saying that he is a boy and so the developmental delays. But co-incidentally he also happened to swallow a plastic toy around that time and while visiting the pediatrician for that, I shared my concerns about his developmental delays. The pediatrician checked and referred to a developmental pediatrician. Through few assessments, they diagnosed him with Autism Spectrum Disorder and auditory intolerance.

SS - My mother-in- law visited us in the US when S was 2 years old. She, like any grandmother, tried interacting with my kids and noticed that S may have developmental delays. Until 2 years of age, it was like S was hitting off all the milestones. He would interact, respond to his name and even follow instructions. It was from 2 years onwards that he started walking on toes even when his shoes were on, and became a very picky eater, especially after he started daycare. We then took him for diagnosis and they said he was on the borderline of the spectrum. We were not given a real picture at all.

SG - G was around 1 year old. He was a very happy, relaxed child. Social smile used to be there, but there was no responding to name or signs of imitation while interacting with my in-laws. Slowly, he started to spin anything and everything he could spin (plate, bicycle wheel). If there was nothing, he would sit and spin himself. He was meeting physical milestones with a 2-3 months delay, so we thought he would be a slow learner or maybe have some difficulty with hearing alone. My in-laws felt there was a delay in development and we also felt he was different from other kids we see around. We visited a pediatrician and he said there seems to be some issue and referred us (to NIMHANS) for diagnosis. There, within 5 minutes he was diagnosed with Autism Spectrum Disorder and we were just told that there is no cure, therapies are the only way to manage and that there are therapy centers where we can go and get more information. I had studied about Autism during my studies but in small detail. I knew it was a childhood disorder, but nothing more. My husband and I were not convinced with the way he was diagnosed and traveled to Mysore to get a detailed assessment done. There he was again assessed in detail, diagnosed and we were briefed about the disorder in good detail.

## Just after diagnosis

What were your feelings and thoughts before and immediately after the diagnosis? Was there a period of uncertainty? 
S-Ish - I was in shock and denial. I knew vaguely about Autism from what we studied as part of our medical course, but nothing much. It was during the before and after diagnosis period when I gathered the information. I would cry almost everyday after the diagnosis. There was a period of uncertainty for about a month. But my sister and husband were very supportive through the process. My sister would send encouraging videos/ resources. My husband believes that any problem will have a solution and he said we would be able to do something. So let’s figure that out. There was now a shift in my career goals. My initial expectation was that my mother would take care of my son and I can complete my Postgraduate (PG) course. Now I had to take a break from my PG course and I decided to take care of the child full time. He became my first priority. I am very glad that I had and have my family’s support. My father was slightly disappointed that I am unable to focus on my career and hoped that I would get back at it.

HM - Only M and I had gone for the assessment while my spouse was at his office. When they provided the diagnosis, I was in shock and sent an SMS to my husband. He also took off for the day and came immediately. M was 1 year and 8 months old then. I was scared, I cried and didn’t eat properly for about a week. My husband also took a week’s time to come to terms with this. We started therapy straightaway at the same center, but we were also trying to seek help from a neurologist, visited temples, made offerings and visited astrologers on the side. That was our period of uncertainty. We also blindly followed whatever was referred to at the center. The professionals we encountered did not give extended support, but they did their work and did not give any false hope either. Other parents sailing in the same boat were my source of comfort at that point.

SS - Soon after he was diagnosed, we came to India thinking he would improve by being around the extended family. We also wanted to check out options available in India. But we couldn’t get any help. Family was not supportive and we couldn’t find the right therapists. It was so frustrating. We were clueless and returned to the US because it felt like there was at least something we could do there. Most people said that he would improve with age and my family members didn’t believe in the idea of therapy. It took me 8 years to accept S’s autism. Meanwhile I would question why this is happening only to me and had a blind hope that S would become normal.

SG - I would say that I didn’t let the diagnosis affect me too much immediately. I thought this is something I know very little of. I need to know more and see what I can try. We were told that there is no cure. That was painful and uncomfortable for almost a year. I was expecting G to be a normal child or at least just a slow learner and what came to us was unexpected. But I did not go to the denial stage. I was aware and accepting of what has come to us. Questions of what next and the confusion were there. On that front, I wish during our first diagnosis itself, they spent a little more time with us to brief us about the condition. My family gave me all the emotional and moral support I required and I am thankful for that. The suggestions thrown at us from different directions to try homeopathy, ayurveda etc., lead us to a confused state and we didn’t know what to do. However, we did not waste much time. We enrolled him for speech and occupational therapy right away. The special education center also provided us with parent training and also we could take counseling sessions. That was helpful. I stopped comparing G with other kids and feeling bad about it.

## Initial steps and alternatives 

What initial steps did you take after diagnosis? What were the alternatives you considered? How did it work out?
S-Ish - We enrolled him in therapy for early intervention but things happening there scared me. Ish would just go into the center, cry and come back. In the occupational therapy assessments, they said he has mild to moderate autism. The occupational therapist suggested a few centers. Speech therapy was difficult to find. In none of the centers we were allowed inside and we didn’t know much about what was happening inside. I would just see the materials used at the center and repeat them at home with my own knowledge. Those were out of my own will. There were no inputs from any of the centers. In one of the centers, they suggested a hands-on training course, but that’s about it. Through different parents we met at different centers, and the therapists, we kept trying different centers for speech, Occupational Therapy and ABA. Most of the parents suggested alternative medicine treatments as well but we didn’t want to go for it due to lack of empirical evidence. 

HM - We continued therapy in the same center for 2 years. M was going to OT and special education. They would tell things we could try at home, but nothing regarding behavior management. We were still clueless about that. It was especially difficult with M, as he had a lot of behaviors. Eating was an issue with him, he would fall sick often, cry constantly and that would also affect me emotionally. He also went to a Montessori school briefly where he would just go, cry in class, jump on the trampoline and come back. We tried two Montessori schools in the hope that if he is in a group, he would pick up some skills. Nothing like that happened. We considered alternative medicine especially for his immunity. We tried homeopathy when he was 6 years old. We also tried a tapping therapy. By then my husband felt that M was not improving. He did the research and we joined a good therapy center.

SS - In India, we couldn’t find anything suitable. We decided to go back to the US and once we were back, we tried HyperBaric Oxygen Treatment and the B12 shot. These were suggested by many people and we learnt from our research that it is safe and does not have side effects. We were told that S might have Attention Deficit Hyperactive Disorder (ADHD). We feel the B12 shot helped S with certain symptoms like hyperactiveness alone. In the US they use sign language with the kids in therapy, by default. There it is more like going with the flow of the child and not pushing them to do anything. We were not satisfied, but we didn’t have many options either. S was also briefly going to daycare where I would drop and the father would pick him. I feel that may have affected our mother son relationship at that point because I would always drop. S also became a picky eater meanwhile. He would eat very selective foods - warm/ food that I cook/ it should be served in a bowl, strictly no milk etc. He went to school along with a shadow teacher while we were in the US, but it wasn’t very effective. We also went through other challenges like having a non-supportive family, and ineffective therapy centers. I did not get any parent training anywhere. Much later, through a friend, we found out about a center in India providing Applied Behavior Analysis (ABA). We relocated and I would say the game changer was when we started writing down the instructions for S. S started following through so quickly. I realized how bothered he was with our verbal inputs. There was also a good set of therapists and structure in place for the kids. The schedule and transparency made me feel comfortable and felt I should have started here earlier.

SG- We started special education early intervention when he was 2 years old and speech and occupational therapy too. He was picking up skills, but we did give in to the influence of other parents of trying new things for 8 months in between. We tried Ayurveda when he was 5 years old. G was naturally a calm kid while we let him be. Through Ayurveda they again gave calming medicines only. So I didn’t see any significant differences. Another major reason I dropped out of it was following the GFCF Diet. G is a foodie and I felt bad in restraining him from so many foods. It was also difficult for me to follow all the time. I then started believing in my efforts and myself for G. 

## Initial sources of information

Where did your knowledge of autism and how to work with it come from initially? Was it helpful? When and where did you find the most useful knowledge?

S-Ish- My knowledge of autism came from the readings I did online. I would watch youtube videos of ABA to work with him at home. What I found particularly helpful was videos made by Chrys Vawnik and Temple Grandin’s Thousand ideas book. My sister would also send articles or videos of autistics doing well in society, to encourage me.

HM - Initially our knowledge of autism came from whatever the professionals were saying, whatever my husband was reading online and whatever I was hearing from fellow parents at the different therapy centers. After joining this therapy center and as I was training to be a therapist, I gained a lot of insight from the theories. ABA Goals gave me an understanding of what I can expect out of my child or any child I am working with. The Verbal Behavior Approach book by Barbara, was helpful for me.

SS - The doctor didn’t give us any clear information. We did our own reading and we would hear from our friends or my husband’s colleagues from the US. We also heard from the therapy centers. I would say nothing was helpful. We didn’t gain any clarity. The readings were mostly from the US websites and it included the US way of looking at children, which didn’t really suit our ideas of children. Colleagues and friends believed it would get better with age. The most useful knowledge I would say came from some readings that my husband did, like looking for alternatives. I would say most of my knowledge of autism came from this therapy center. That is where I got a real picture of my son.

SG - The first knowledge I got was from the center at Mysore where I took G for a detailed assessment. At AISHA, they gave us detailed information. Other sources of my knowledge also included friends who also have autistic kids, other parents I met anywhere in the public. They were helpful. I did not hide my kid. He would come with us everywhere. That opened new conversations and new ideas. That way I also was learning to handle G in different environments and that also let me know what I can expect out of my child. I think I can say that I relied more on the knowledge I gained from real experiences of people than textual or theoretical knowledge. Apart from that, I also gained more understanding when I did my RBT course and training and while I worked with other kids. The RBT theory really helped me understand things from the kid’s perspective.

## Early intervention choices and impact

What early intervention did you settle on and how did it impact you and your child?

S-Ish - I was always on the lookout as I was not completely satisfied with the therapies I was receiving. He was going for OT, Speech and other therapies where there used to be some schedule and goals. Everywhere it felt like we were paying a lot of money, Ish was going inside, crying and coming back. At that point, I did not see crying behavior as a part of the learning process. We were a little unsettled because nowhere we were allowed inside and there was not much clarity. We also sent Ish to school. He attended LKG and UKG with a shadow teacher. My initial goals were that Ish should speak, should not cry and behave well, and that he should attend a mainstream school. These were the goals I had for him until he was 6 years old. After that, he started to communicate which I was happy about. By then he also acquired certain patterns and I had a shift in my goals. By then his OT was also going alright. The therapist gave home plans and some ABA tips. I was still seeking help with other therapies and asked for suggestions as I did not know how to manage at home. The therapist then referred me to this therapy center for ABA.. Since it was transparent and we were given a clear picture here, we felt more settled. At no point, I gave up working on him. Meeting parents who were confident gave hope that they must be doing something right. So I would seek their help. My family was very supportive through this process. My husband would say decide whatever is working for you and do that, we’ll support you. My mom and sister were always available for me. Financially also we didn’t have challenges. That was a big plus point for us. We also sent Ish to other classes like the Kumaon class where they teach the Japanese method of learning math and english. I stopped OT and started physical training instead when he was 7 years old.

HM - We started with special education, but since we did not see any improvement, we shifted to ABA. We knew about ABA before, but financially we were not sure if we could support it long term. While shifting we thought we’ll see for 2 years and then we could homeschool. I wish we had started earlier. M underwent food intervention as he was not eating properly. Even to get him to drink water was a struggle. But once we cracked it, it opened up new skills and learnings for M. His sitting tolerance increased and hyperactivity went down. With the schedule in place, his anxiety also went down. We were very happy with the progress he was making.

SS - We settled on whatever was provided in the US. They were doing ABA, but quite different from what is being offered here. They used sign language for communication predominantly with kids who were not fluent. He was picking vocabulary from Disney movies and would then use that for communication. He started talking again by the time he was 8 years old. Until then his school provided speech therapy and Occupational therapy. I wish we found this therapy center earlier and started off here.

SG - Special education. It worked for G. He picked up a few skills. Even though it was slow, he was picking up things until I decided to put him in a preschool after 1 year of early intervention, going with the suggestion of his special education therapy center. I feel like he might have regressed there. He dropped even the few skills he had picked up. He was still continuing Occupational Therapy and Speech Therapy, so things were alright at that front. I removed him from the preschool and enrolled him in another special education therapy center itself for another year before going for ABA.

## Moving on from early intervention

When did you feel early intervention had run its course and you needed to move on? Why?
S-Ish - He was 7 years old, getting educated and trained in different things, but we did not know what next for him. School was not working. What next in life, in academics, in leisure skills etc. were new questions that popped up. COVID hit and for 2 years he was taking online therapy. Simultaneously the learning community space opened and some parents I know were already a part of it. Since we were getting full time parent training there, we also decided to join the community learning space.

HM- We kept trying different things throughout but I realized that I am unable to be consistent at home. Managing household chores and M was becoming overwhelming. The consistency was limited only to the therapy center. COVID hit and that’s when the realization hit as well. We realized that we can’t homeschool him like we planned while joining ABA. There has to be something else. This learning community space opened and we thought that would be the next best option.

SS -Through the 8 years we were constantly in the lookout for something better as we were not satisfied with what was being offered in the US. That’s when we got to know of this therapy center and we had our initial discussion with the founders of the center. 

SG - He was 6 years old and I felt like he was still not picking any skills. He was still dependent on us for a lot of things. He wasn’t even potty trained. So all of these were concerning and I started looking out for other options when I landed at this therapy center through a friend.

## After early intervention

What were your next steps? What have you been doing over the last few years? How has your journey been?

S-Ish- It was not until I moved to the community learning space that I realized how prompt dependent Ish  had been. Even with things I thought he was independent, I realized he is prompt dependent and not really independent. With being in such a space full time, came more awareness and knowledge. I had revised my goals for him by now. I wanted him to be able to express his feelings, have leisure skills where he is independent and that he should be able to manage himself even if I am not around. He should be able to work and be with other teachers/ therapists/ parents. I realized that each autistic kid is different and each of them are good at something of their own. We should provide the space to enhance those skills and encourage them. My journey has been full of learning that way and I feel like I am on my right path. When I look back, I feel hopeful. I have been able to achieve goals I had for myself and I see that Ish is also going there. An advice that has stuck with me is that we should have set goals for another 5 years and then we can work towards that. This advice has made me rethink the beliefs I had.

HM- We joined the community learning space and his food intervention continued in full swing. I figured that I am able to be much more consistent here and also bring in new ideas and goals as I interact with others and work with other kids. M also improved a great deal. He started to explore more food items. With that, he also became more open to other things. He started to pick up new skills like cycling, gardening etc. It has been a great learning journey for the both of us. We have new goals as he progresses. I also have the space to work on myself and set things in my own life.

SS - We booked our tickets to India after knowing about this therapy center. Unfortunately COVID hit and we had to wait for another 3 years before we moved to India. S was taking therapy at the early intervention center in order to be prepared to move into the community learning space. We were just waiting to know that he was ready. My youngest kid was also becoming a picky eater so I sought food intervention alone for him and now he is also here with us at the learning community. It is working well for us that way except that our oldest kid misses on the time he would get to spend with us. But he also sees the point of this now and he is okay. The siblings spend their time together during the weekends. I see a great deal of improvement in S and I am very happy I am here.

SG - We started ABA and there was no going back, It took 1 year for him to be potty trained by following schedules. The structured program in the center was very helpful. I could see a lot of changes in him within that 1 year. He already had some sitting tolerance and he used to follow instructions. But things improved with ABA and the introduction of AVAZ. The 3 mantras I would say that has worked wonderfully with G are structure, schedule and consistency. I also got the opportunity to be trained as an RBT and it has been a good experience for me. Getting to work with other children was rewarding and at the same time provided hope to work with my child. When you see the fruit for the work you put in, it is highly motivating. After ABA I tried group therapy for G for 1 year in between, but it wasn’t very effective. Then COVID hit and we were working online and I was working with him at home. We are now a part of this homeschooling community where again I get to work with other kids and I am learning new things. G also gets to learn in a group and with new challenges, comes new learnings for the both of us.

## Managing self and family

How did you manage yourself and your family during this period?
S-Ish- Since my family has always been supportive, it didn’t feel like a big deal. Everyone else adjusted according to our needs. My decision and my clarity was enough for all of them. My mother even moved closer to our house to help me out as I was juggling between different therapy centers. I wanted to get back to my career at some point but those thoughts came slowly as and when we were feeling slightly settled. I got to complete my PG course as well. Now I am able to leave Ish and go away for my work at least for a few hours and then come back. I feel like I have come a long way.

HM - My family was not very supportive. It was just my husband and I. I started attending to M full time. It was becoming overwhelming to manage household chores and M at home. I lacked the motivation to follow through M’s interventions even though I knew what had to be done. Now I have come a long way and learnt so many things. I plan and organize my work better in order to balance my personal work and M’s works. I also take or ask for help actively. I have learnt to do that and I am grateful.

SS -  I dedicated myself to my family. I wish I had said no to other commitments now. I couldn’t fully focus on S because of the other commitments. Right now, I am happy we are here. My youngest kid is also getting the right education and S is getting to be with him as well. So I am happy, going with the flow. Kids are my 1st priority for now and right now it is S. I have wasted a lot of time already and do not want to waste anymore.

SG - I made up my mind that now I will have to spend more time with my kid. I had to give up on my career as a lecturer, but I don’t regret it. I feel I can get back to it anytime, right now G is my focus. And I don’t feel whatever I'm doing currently is very different from what I wanted to do. I wanted to go to the hospital and work at some point, I would be serving the older population there, here I am serving the child population. My in-laws and husband were very supportive. I had difficulty managing time for the first 1 year then I learnt to prioritize. My family has supported me and my decisions consistently. They also learn the interventions and that helps in being consistent with G. They took time to accept AVAZ, but it wasn’t very difficult to convince them when I stayed put.

## Future - Hopes and apprehensions

What are your hopes and apprehensions as you think of the future?

S-Ish - My journey is making me feel hopeful about the future as well. Now Ish is able to manage himself while I attend meetings and I am able to focus on my career as well while I am able to trust and leave him in the learning community. His learning is also not hindered. Goals are set and we are moving towards his goals as well while meeting our personal goals. I hope he will be in a position to manage our hospital reception at some point. Not much apprehension at this point in time. I used to be worried about him hitting or getting aggressive when he gets upset or angry. Now that we have been able to manage that, it all feels like it can be managed.

HM - M touches himself right now. That scares me, but at the same I am hopeful that we will figure out how to manage that as he is in a safe space now to learn that. I am slightly apprehensive of what he is going to be in the future, but at the same time in the mindset of whatever can be done in the present with him, let’s do it and see where it is leading.

SS - As he is approaching adolescence, some fears and questions I have are about him managing his private space and understanding personal boundaries. He is still learning to close doors while he dresses up or to respect a closed door when others are dressing up. I hope he builds enough motor skills to protect himself and the question of what and who after me is lingering in my mind. I do not want S to be dependent on his siblings nor do I want the siblings to feel obliged. Also the thought of “What if he gets physical when he is angry?” scares me now.

SG - I see people are more aware now and they provide support wherever and whenever they can. That makes me feel hopeful, but I would like for G to be independent with his life skills at least. My apprehensions are also on the same lines. Not all people will be the same. So that fear of how society would treat him, would they take advantage of his challenges are some questions I have in mind. Right now he is not completely independent, but I expect him to get to a stage where he can take care of himself. I also see new interests popping up as we expose him. So I am now open to exploring his interests with him and if he is able to pick on them, we as parents are ready to completely support him.

## Advice for new parents

What advice would you give parents of newly diagnosed children?

S-Ish - I feel parents have to go through their own journey in order to gain an understanding of their kid’s autism and how the family has to work around it. But be involved with your kid. Put in the hard work, time and effort. If you have the chance to work with other autistic kids, it would enhance your understanding of autism. So take up such opportunities. Seek community support. It has been very helpful for us. I would also advise them to reach out to parents who are encouraging especially in the beginning stages as they give hope. Start as early as possible. Therapy is the best thing to do, but do some research as well as to what would work for the child and the family. According to me, the most important thing of all is to take support from wherever and whenever possible.

HM - Start with ABA. There is no cure to Autism, but it is manageable. So have hope in that and continue to work. Don’t waste time and money on offerings/ astrology/ priests etc., while you are still figuring out Autism.

SS - Be strong and give all your attention to your kids while they are growing up. Don’t wait for a miracle to happen, it is not going to happen. Instead, work with your kid.

SG - I know and understand that it will be very difficult to accept in the first because of the various expectations we formed as we were giving birth to the child, but eventually accept it with confidence. End of the day, this is still our kid. Be consistent with your effort and go ahead. Don’t think like there is no life forward or nothing can be done. There will be positive sides, so try and look at them. With our kids, even little things make a lot of difference. Enjoy them!
Also, do not just aim to put them in a normal school. Think through your decisions and think from the child’s perspective as well. Do what would be best for the child. Our children’s needs are different.
