---
format:
  html:
    include-after-body:
       - "_includes/load-comments.html"
---

# People on The Spectrum


## Video - Unmasking the Stigma Behind Autism in Females | Emmy Peach | TEDxUGA

Emmy Peach, who got diagnosed at the age of 19 shares that even though her brother was diagnosed when he was 2, she was not because traditional diagnostic criterias are based on male presentations of autism. She adds that girls also learn to mask at a younger age which becomes more difficult to get help. 

She talks about the impact of being diagnosed and the persistent stigma around autism. She encourages unmasking, embracing neurodiversity, and being authentic.

{{< video src="https://www.youtube.com/watch?v=7KPK5sMar5w&list=PPSV" >}}

## Video - Why autism portrayal is one-dimensional—and how to change it

This Ted talk video is about the experiences of Chloe Hayden, an actress on the spectrum. The below are a few key points that Chloe talks about in the video.
- The mainstream portrayal of autism in the movies, series and media is problematic
- There is harm in viewing autistics as only people who can or can not contribute to the capitalist society
- Chloe emphasizes on listening to autistic people
- She also stresses on valuing people for the way they are and that it is okay to "just be."

{{< video src="https://www.youtube.com/watch?v=wKUDd58CrY4&list=PPSV" >}}
