title: Autism Bharat
site_url: https://autism-bharat.org

navbar:
  links:
    - label: Home
      href: /
    - label: About
      href: /about/

footer:
  copyright: © 2024 [Farmhill Education Trust](https://farmhill.in) | Licensed under Creative Commons
  sections:
    - title: About This Guide
      entries:
        - label: About this Project
          href: /about/
    - title: Key Topics
      entries:
        - label: Understanding Autism
          href: /understanding-autism/
        - label: A guide to Happy Haircuts
          href: /resource-haircut/
        - label: Eating Interventions
          href: /resource-eating/

    - title: Supporting Organizations
      entries:
        - title: Azim Premji Foundation
          href: https://azimpremjifoundation.org/
        - title: Action for Autism
          href: https://www.autism-india.org/
        - title: Ummeed
          href: https://www.ummeed.org/
        - title: Sethu
          href: https://sethu.in/

