# Understanding Autism - A video from Sethu 

Here is a video on "Understanding Autism" from [Sethu](https://sethu.in), a child development and family guidance center based in Goa. This video talks about the importance of getting a diagnosis, the causes of autism, and the challenges faced autistic people.

A brief summary of the video in bullet points:

-   Autism exists everywhere
-   Getting a diagnosis means that you now have the chance to access the right kind of intervention program for your child
-   There is no known cause of autism, but we know that it's nothing that you or anyone did that has caused your child to be autistic
-   It is a spectrum disorder, and your child is unique in terms of their strengths, interests and challenges
-   Your child experiences the world around in a very different way
-   Autistic children need support with their social communication and social interaction skills
-   They have a difficulty in processing all the information that their senses are taking in
-   Autism is not the same as an intellectual disability
-   Autism is not a disease, and it does not need a cure

*Note*: The video talks about understanding autism as "piecing together the puzzle". It may be useful to note that the puzzle analogy for autism is not approved by all the people living on the spectrum.

{{< video https://www.youtube.com/embed/HeG6T_4jKrk >}}